cp programa_ejemplo.tex 709-Doc-AprendizajeAutomatico.tex
cp programa_ejemplo.tex 734-Ms-AprendizajeAutomatico.tex 
cp programa_ejemplo.tex 712-Ms-AnalisisYDisenoDeAlgoritmos.tex
cp programa_ejemplo.tex 687-Doc-AnalisisYDisenoDeAlgoritmos.tex
cp programa_ejemplo.tex 725-Ms-CienciaDeLosDatos.tex           
cp programa_ejemplo.tex 699-Doc-CienciaDeLosDatos.tex
cp programa_ejemplo.tex 735-Ms-ComplejidadComputacional.tex
cp programa_ejemplo.tex 402-Doc-ComplejidadComputacional.tex
cp programa_ejemplo.tex 150-Ms-InteligenciaArtificial.tex  
cp programa_ejemplo.tex 415-Doc-InteligenciaArtificial.tex
cp programa_ejemplo.tex 726-Ms-ProcesamientoDeImagenesYVisionComputacional.tex
cp programa_ejemplo.tex 700-Doc-ProcesamientoDeImagenesYVisionComputacional.tex
cp programa_ejemplo.tex 699-Ms-Seminario1.tex                                  
cp programa_ejemplo.tex 702-Ms-Seminario2.tex
cp programa_ejemplo.tex 654-Doc-SeminarioDoctoral1.tex
cp programa_ejemplo.tex 657-Doc-SeminarioDoctoral2.tex
cp programa_ejemplo.tex 660-Doc-SeminarioDoctoral3.tex
cp programa_ejemplo.tex 663-Doc-SeminarioDoctoral4.tex
cp programa_ejemplo.tex 667-Doc-SeminarioDoctoral5.tex
cp programa_ejemplo.tex 670-Doc-SeminarioDoctoral6.tex
cp programa_ejemplo.tex 673-Doc-SeminarioDoctoral7.tex
cp programa_ejemplo.tex 676-Doc-SeminarioDoctoral8.tex
cp programa_ejemplo.tex 708-Ms-SimulacionDeSistemas.tex
cp programa_ejemplo.tex 683-Doc-SimulacionDeSistemas.tex
cp programa_ejemplo.tex 698-Ms-Tesis1.tex             
cp programa_ejemplo.tex 701-Ms-Tesis2.tex
cp programa_ejemplo.tex 652-Doc-Tesis1.tex
cp programa_ejemplo.tex 655-Doc-Tesis2.tex
cp programa_ejemplo.tex 658-Doc-Tesis3.tex
cp programa_ejemplo.tex 661-Doc-Tesis4.tex
cp programa_ejemplo.tex 664-Doc-Tesis5.tex
cp programa_ejemplo.tex 668-Doc-Tesis6.tex
cp programa_ejemplo.tex 671-Doc-Tesis7.tex
